export const API_URLS = {
  login: "api/login",
  getUserInfo: "api/getUserInfo",
  searchCustomer: "api/searchCustomer",
  getKaniShindanInfo: "api/getKaniShindanInfo",
  getListProductByUser: "api/getListProductByUser",
  updateKaniShindanInfo: "api/updateKaniShindanInfo",
  getListAgent: "api/getListAgent",
  updateCustomer: "api/updateCustomer",
  deleteCustomer: "api/deleteCustomer",
  getSelectItem: "api/getListSelectItem",
  getListImage: "api/getListImage",
  uploadFileRelation: "api/uploadFileRelation",
  getListMessage: "api/getListMessage",
  sendMessage: "api/sendMessage",
  searchRiyo: "api/searchRiyo",
  searchHaishinLog: "api/searchHaishinLog",
  searchMessage: "api/searchMessage",
  haishinLogUpload: "api/haishinLogUpload",
  messageImageUpload: "api/messageImageUpload",
  getListFileUpload: "api/getListFileUpload",
  createHaishinlog: "api/createHaishinlog",
  getHaishinLogDetail: "api/getHaishinLogDetail",
  getProductByKeiyakuno: "api/getProductByKeiyakuno",
  searchTargetCustomer: "api/searchTargetCustomer",
  sendKeiToSystem: "api/sendKeiToSystem",
  deleteFileUpload: "api/deleteFileUpload",
  getMessageImg: "api/getMessageImg",
  getCustomerInfo: "api/getCustomerInfo",
  deleteFileRelationUpload: 'api/deleteFileRelationUpload',
  getFilePdf: 'api/getFilePdf',
  getListKeiyakuHosho: 'api/getListKeiyakuHosho',
  getListHosho: "api/getListHosho",
  getListTokuyaku: "api/getListTokuyaku",
  getListCompany: "api/getListCompany",
  getListProduct: "api/getListProduct",
  createAgent: 'api/createAgent',
  ocrRequest: "api/requestOCRList",
  delOcrList: "api/deleteOCRList",
  getListFamily: "api/getListFamily",
  getCustomerAgent: "api/getCustomerAgent",
  processKeiyakuAuto: "api/processKeiyakuAuto",
  getListAgentByUserNo: "/api/getListAgentByUserNo",
};
export const ROUTER_URL = {
  login: "login",
  customerSearch: "customer-search",
  productsFamily: "products-family",
  productsCategory: "products-category",
  productDetail: "product-detail",
  productImage: "product-image",
  messageList: "message-list",
  messageSend: "message-send",
  analyzerInfo: "analyzer-info",
  historyInfo: "history-info",
  messagesAwait: "messages-await",
  messagesDetail: "messages-detail",
  messageReply: "message-reply",
  messagesTarget: "messages-target",
  messagesTargetChose: "messages-target-chose",
  messagesTargetDetail: "messages-target-detail",
  ocrDetail: "ocr-detail",
  ocrRequest: "ocr-request"
};
export const RESULT_CODE = {
  success: "001",
  DUPLICATE: "400",
  AUTH_FAIL: "401",
  NOT_EXIST: "404",
  REQUIRED: "101"
};
export const CONST_CODE = {
    imageUpload: 'image/jpeg',
    imagePdf: 'image/jpeg,application/pdf'
}
export const MONTH_FORMATS = {
  parse: {
    dateInput: 'YYYY/MM',
  },
  display: {
    dateInput: 'YYYY年MM月',
    monthYearLabel: 'YYYY MMM',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'YYYY MMMM',
  },
};